<?php
/**
 * @file
 * Mus api key management and search api hooks.
 */
define('MUSSEARCH_MAPPING_CSV', 'config/mapping.csv');

/**
 * Implements hook_menu().
 */
function mussearch_menu() {
  $items = array();

  $items['admin/config/search/musapimap'] = array(
    'title' => 'MuSapi map utility',
    'description' => 'MuS search map utility to create map and schema.xml file',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mussearch_map_utility'),
    'access arguments' => array('administer mus api'),
    'file' => 'mussearch.admin.inc',
  );
  $items['admin/config/search/musapikeys'] = array(
    'title' => 'MuSapi api key management',
    'description' => 'MuS search api key management allows to manage api keys',
    'page callback' => 'mussearch_apikey_management',
    'access arguments' => array('administer mus api'),
    'file' => 'mussearch.admin.inc',
  );
  $items['admin/config/search/musapikeys/%'] = array(
    'title' => 'MuSapi api key management',
    'description' => 'MuS search api key management allows to manage api keys',
    'page callback' => 'mussearch_apikey_management',
    'page arguments' => array(4),
    'access arguments' => array('administer mus api'),
    'file' => 'mussearch.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function mussearch_permission() {
   return array(
    'administer mus api' => array(
      'title' => t('Administer MuS search api'),
    ),
  );
}

/**
 * Change the way the index's field names are mapped to Solr field names.
 *
 * @param $index
 *   The index whose field mappings are altered.
 * @param array $fields
 *   An associative array containing the index field names mapped to their Solr
 *   counterparts. The special fields 'search_api_id' and 'search_api_relevance'
 *   are also included.
 */
function mussearch_search_api_solr_field_mapping_alter(SearchApiIndex $index, array &$fields) {
  $field_mappings = mussearch_get_solr_fieldmappings();
  if ($index->item_type == 'node' && is_array($field_mappings)) {
    foreach ($field_mappings as $key => $value) {
      if (isset($fields[$key])) {
        $fields[$key] = $value;
      }
    }
  }
}
/**
 * Utility functions
 */

/**
 * Get the solr field mappings
 */
function mussearch_get_solr_fieldmappings() {
  $field_mappings = parse_ini_file('fieldmappings.map');
  return $field_mappings;
}
