<?php 

/**
* Implements hook_entity_info_alter().
*/
function adlib_display_entity_info_alter(&$entity_info) {
	$entity_info['node']['view modes']['adlib_object'] = array(
    'label' => t('Adlib object list view'),
    'custom settings' => FALSE,
	);
}

/**
* Implements hook_preprocess_node().
*/
function adlib_display_preprocess_node(&$vars) {
	if($vars['view_mode'] == 'adlib_object') {
		$vars['theme_hook_suggestions'][] = 'node__' . $vars['type'] . '__adlib_object';
	}
}